### ISSUE TITLE
EXTI on STM32L0_GPIO_PIN_PA4 clasheds with LoraWAN

### ISSUE THREAD

**Issue by SloMusti** [GrumpyOldPizza/ArduinoCore-stm32l0#102]
Exploring the option to enable external interrupt on STM32L0_GPIO_PIN_PA4, like it is defined for https://github.com/GrumpyOldPizza/ArduinoCore-stm32l0/blob/45b40b96751e01bfe23a1151ce8457b31f363c3d/variants/P-NUCLEO-LRWAN1/variant.cpp#L63 results in the following behavior:

PA4 external interrupt works until a LoraWAN transmission occurs. Then it stops working and likely affects LoraWAN operation as well. On some board definitions there is no EXTI for PA4. @GrumpyOldPizza what is the reasoning behind this?

Minimal code example attached to try this.
[LoRaWAN_TTN_ABP_PA4_EXTI.zip](https://github.com/GrumpyOldPizza/ArduinoCore-stm32l0/files/3564824/LoRaWAN_TTN_ABP_PA4_EXTI.zip)

**Comment by GrumpyOldPizza** [comment]
Yje Murata modules is using PB4/PB0/PB1 internally for the DIO0/DIO1/DIO2 interrupts.PA4 conflicts with that. Hence the variants with this module do not allow EXTI on that (i.e. a attachInterrupt()).
