### ISSUE TITLE
Question: Is there a Capacitive Sense example for STM32L082XX?

### ISSUE THREAD

**Issue by applecrusher** [GrumpyOldPizza/ArduinoCore-stm32l0#106]
According to the STM32L082 documentation on page 28, [STM32L082 datasheet](https://www.st.com/resource/en/datasheet/stm32l082kb.pdf), the STM32L082 has the ability to do capacitive sensing. Is there an example of this in the repository? Other capacitive sensing libraries I have tried such as this [one here](https://www.arduinolibraries.info/libraries/capacitive-sensor), are not compatible and give me a complication error. 

Note: I am using the Grasshopper LoRaWAN development board: https://www.tindie.com/products/tleracorp/grasshopper-loralorawan-development-board/

**Comment by GrumpyOldPizza** [comment]
The TSC controller is not yet supported. At the end of the day, the available pins do not really lend themselfs to TSC capability.

**Comment by applecrusher** [comment]
Thank you! If possible, can you elaborate on the second sentence? I have never done capacitive sensing and would greatly appreciate your input.

**Comment by GrumpyOldPizza** [comment]
Please consult the documentation for the TSC peripheral and the availble TSC groups/pins on the Murata module ...

**Comment by applecrusher** [comment]
Will do. Thank you.
