### ISSUE TITLE
Question: Is it possible to shorten the LoRaWAN transmission time to less than 3 seconds by changing default parameters?

### ISSUE THREAD

**Issue by applecrusher** [GrumpyOldPizza/ArduinoCore-stm32l0#109]
I am trying to send burst messages to a LoRaWAN gateway as fast as possible. However, it seems that it takes exactly 3 seconds to complete the transmission and execute the callback.  Is there a way to shorten this duration by changing one of the default parameters?

**Comment by GrumpyOldPizza** [comment]
No. Please check out the official LoRaWAN specificaion.
