### ISSUE TITLE
examples compile error

### ISSUE THREAD

**Issue by ucdos123456** [GrumpyOldPizza/ArduinoCore-stm32l0#11]
when i use arduino IDE 1.8.5 compile LoRaWAN example by B-L072Z-LRWAN1, it shows "
# exec: "/bin/arm-none-eabi-g++": file does not exist"

i'm not sure what's the problems.

**Comment by GrumpyOldPizza** [comment]
My bad. With installations from github you need to install the SAMD core to
suck in the compiler.
