### ISSUE TITLE
Strange Join Issues

### ISSUE THREAD

**Issue by hallard** [GrumpyOldPizza/ArduinoCore-stm32l0#112]
I've got multiple TTN Gateways (EU 868) around and noticed sometimes that join can take minutes.

This is really strange because sometimes it join quickly and sometimes not, could it be related to limited downlinks by TTN?

Anyway, and my question, is there any issue doing some ```STM32L0.stop(anyDelay)``` until we joined the network ? Does the stack still working async whatever we do in `loop()`

**Comment by GrumpyOldPizza** [comment]
You might want to check with your gateway, whether it sees the join requests or not ... 

Regarding STM32L0.stop() and sich. Yes, the LoRaWAN stack works async in the background (also switching between RUN/SLEEP/STOP).

**Comment by hallard** [comment]
Thanks for the explanation.
The join request goes to TTN I can see on TTN dashboard but that's all. I suspect it occurs when there is more than one GW sending to TTN. Need to do further investigation and also test on my own LoRaWAN server to see.

**Comment by hallard** [comment]
I tested on my private LoRaWAN server and it works like a charm, after each reset of the board join is accepted immediately in a couple of seconds. So I tried back on TTN and tooks minutes.
So I decided to remove this line (found in some examples) that I don't know why it was for and only for TTN, but given a try
```
LoRaWAN.addChannel(1, 868300000, 0, 6);
```
Guess what, now it is joining immediately each time, so I think you can remove from examples.

**Comment by GrumpyOldPizza** [comment]
Can I close this out now ?

**Comment by hallard** [comment]
I could add your trick for 20ms error as a sample but may be best to wait this function in the framework so I can post an example here and close the issue?

**Comment by GrumpyOldPizza** [comment]
Added a new API to the LoRaWAN class:

LoRaWAN.setSystemMaxRxError(millis);

The default is 10ms.
