### ISSUE TITLE
# of timerMillis() instance

### ISSUE THREAD

**Issue by hallard** [GrumpyOldPizza/ArduinoCore-stm32l0#113]
Just to be sure, Is there any limitation on timerMillis() instance?

I added one (the fourth) and looks like my previous events are not fired anymore. Just to be sure it's not limited.

**Comment by GrumpyOldPizza** [comment]
There is no limit on the number of TimerMillis instances.

**Comment by SloMusti** [comment]
@hallard I have observed similar behavior as well, have resulted in rewriting the code to use lezz of TimerMillis

**Comment by hallard** [comment]
Would love to have something like in the L4 framework, so easy and rocks
https://github.com/GrumpyOldPizza/arduino-STM32L4/issues/17
