### ISSUE TITLE
SoftwareSerial

### ISSUE THREAD

**Issue by Sestre-oratek** [GrumpyOldPizza/ArduinoCore-stm32l0#115]
Hi there,

Thanks for your job.

I need to use the pins D3 (39) and D4 (38) of the STM32L0 for serial communication. For Arduino boards, "SoftwareSerial" exists to use other pins that 0 and 1 for TX and RX. Is that a way to use this library "SoftwareSerial" with the STM32L0? Or another easy way to do it?

If not, are there any plans to implement this in the future?

Thanks a lot!

**Comment by GrumpyOldPizza** [comment]
Software Serial is not supported and will not be supported. It assume that there are never interrupts while you send/receive. GIven the complex networking stack (and other background activities), this is not supportable.
