### ISSUE TITLE
Just want to confirm which LoRaWAN version corresponds to this implementation

### ISSUE THREAD

**Issue by jarodcs** [GrumpyOldPizza/ArduinoCore-stm32l0#121]
Hello everyone, thanks to the developer for this library.
As the subject title says, I would like to know which LoRaWAN version this implementation supports. I read on the description "Complete LoRaWAN library for Class A, 1.0.2B strandard".

Does it mean that it supports the following specs:
- [https://lora-alliance.org/resource-hub/lorawanr-regional-parameters-v102rb](https://lora-alliance.org/resource-hub/lorawanr-regional-parameters-v102rb) and
- [https://lora-alliance.org/resource-hub/lorawanr-specification-v102](https://lora-alliance.org/resource-hub/lorawanr-specification-v102)

Thanks in advance for your answers.

**Comment by GrumpyOldPizza** [comment]
Yes.
