### ISSUE TITLE
I need two USART's to transmit data using LoRaWAN

### ISSUE THREAD

**Issue by meakash** [GrumpyOldPizza/ArduinoCore-stm32l0#122]
Receiving sensor data on uart 2 it is not working properly (i have yo press the reset button continuously to work) so can you please suggest a work around and some tips to about how can i send two sesnor data using uart 1 and uart 2 through lorawan

I am using and STM32L072(B L072 LRWAN)

**Comment by GrumpyOldPizza** [comment]
Not sure where the problem is. There is one UART on D0/D1 and one UART on D2/D8.
