### ISSUE TITLE
Interrupts

### ISSUE THREAD

**Issue by rmeldo** [GrumpyOldPizza/ArduinoCore-stm32l0#13]
Hi, 
Do the interrupts work?
I am trying to find out which pins are enabled for using them.

Thank
Riccardo

**Comment by GrumpyOldPizza** [comment]
Interrupts work.

All Dxx pins allow interrupts. I need to come up with some better
documentation there though.

- Thomas

**Comment by rmeldo** [comment]
Thanks, 
I found out that the High and low options are not supported, whereas rising, falling and change work, and they are what's needed most of the time.
Riccardo

**Comment by GrumpyOldPizza** [comment]
Issue is that LOW and HIGH are not supported for STM32L0.

The semantics are that a interrupt get triggered as long as a pin has the selected level. Hence at enable time the code had to check (and pend the ISR) the GPIO. At the tail of the ISR handler one had to also check the GPIO and if the level is still matching, re-pend the ISR.

Try to get this added in a bit. IMHO this is not really that useful I'd assume, but it should be there for compatibility.

**Comment by rmeldo** [comment]
I see your point and agree.
Once you are in the ISR you can keep checking the level until you're sure
it is low and act accordingly, or exit without acting.

I also agree that for compatibility it is desirable to have the High and
Low options.

Riccardo

**Comment by ucdos123456** [comment]
@GrumpyOldPizza 
Hi. i redefine D1 to PA13. Do this pin supports interrupt?

**Comment by GrumpyOldPizza** [comment]
PA13 supports interrupts. But PA13 is also a SWD pin. So you lose the ability to debug the system ...

**Comment by paengpd** [comment]
Hi,
' All Dxx pins allow interrupts. '
Other pins are not work? Only Dxx pins are available?
ex) A0~A4, SCL, SDA...

**Comment by GrumpyOldPizza** [comment]
A0 to A4 should work as well, plus/minus aliasing (PA2 would alias with PB2, which means only one of them can be an interrupt). Do not use interrupts on SCL/SDA, ever. They are I2C pins, sometimes with internal peripherals mapped.

**Comment by hallard** [comment]
Yes I confirm, even with no I2C device and not enabled with `wire`, on grasshopper IRQ on SDA works but not on SCL

**Comment by GrumpyOldPizza** [comment]
My bad. Need to fix the variant.cpp files. PA8 aliases PB8, so PB8 cannot have a interrupt. Same goes with PA9 and PB9. So neither SDA nor SCL should have interrupts on them.

**Comment by hallard** [comment]
It's no problem, I wanted to use my 2 I2C exposed pin as IRQ for a demo without changing anything on my board. So I used another pin as other Interrupt but I have no more left, so I'm happy SDA works ;-)

**Comment by sanketa-54** [comment]
Hi
Can we use attachInteruupts on pin PA13 and PA14

**Comment by GrumpyOldPizza** [comment]
Yes, but not recommended, as PA13/PA14 are SWD.

**Comment by sanketa-54** [comment]
Ok...Thanks for reply.

**Comment by sanketa-54** [comment]
Also PB13 and PB14 are supported for attachInterrupt() ??
if yes , is there anything to be done in variant.cpp file 

These two pins are shorted .
Any pins interrupt support is ok for me
