### ISSUE TITLE
LoRaWAN "gateway" type receive function

### ISSUE THREAD

**Issue by SloMusti** [GrumpyOldPizza/ArduinoCore-stm32l0#132]
For some experimental applications, it would be useful to be able to specify channel and SF and receive the LoRaWAN packet. This does not appear to be feasible just now with the library, but could be to some extent implemented with LoRaRadio. The issue is however that without a reboot, switching between LoRaRadio and LoRaWAN in runtime does not work.

@GrumpyOldPizza do you have any good suggestion how to goa bout this without too much work?

**Comment by GrumpyOldPizza** [comment]
There is no good way to handle this at the moment.

**Comment by GrumpyOldPizza** [comment]
Closing out. Much of this might be resolved by moving to a new LoRaMac-node source base.
