### ISSUE TITLE
Incorrect size check in FskRadio setSyncWord()

### ISSUE THREAD

**Issue by petinox** [GrumpyOldPizza/ArduinoCore-stm32l0#135]
Currently not possible to change sync word in FSK mode, tested with SDR. I suspect the size check referenced below should be "< 1" instead of "> 1".

When inequality is changed in FskRadio.cpp, setting sync word works as expected.

https://github.com/GrumpyOldPizza/ArduinoCore-stm32l0/blob/c845a3b4b90b8a8fe95c6fedd4fa927dae14ba45/libraries/FskRadio/src/FskRadio.cpp#L696

**Comment by GrumpyOldPizza** [comment]
Will fix in the new commit.

**Comment by GrumpyOldPizza** [comment]
Fixed.
