### ISSUE TITLE
ContinuousWave mode for RF Performance Testing

### ISSUE THREAD

**Issue by ThomasBaumgartner** [GrumpyOldPizza/ArduinoCore-stm32l0#136]
It's more a question rather than an issue. Does this stack currently support the activation of the CW-Mode through MAC-Layer commands as requested by the LoRaAlliance for RF Performance measurement purpose? 

Meaning if the device receives a payload with initial value 0x07 on port 224 it enables CW-Mode and uses the following bytes in the payload to determine timeout, frequency and Tx power.

**Comment by GrumpyOldPizza** [comment]
Mind contacting me directly about that via grumpyoldpizza@gmail.com ?

**Comment by GrumpyOldPizza** [comment]
Added as API. 

int setTxContinuousWave(unsigned long frequency, float power, unsigned long seconds);
