### ISSUE TITLE
LoRaWAN custom preamble length

### ISSUE THREAD

**Issue by SloMusti** [GrumpyOldPizza/ArduinoCore-stm32l0#139]
The support for custom preamble length would be useful for experimentation, however that is not required as this is statically defined for each frequency band.

LoRaRadio preamble is supported: https://github.com/GrumpyOldPizza/ArduinoCore-stm32l0/blob/c845a3b4b90b8a8fe95c6fedd4fa927dae14ba45/libraries/LoRaRadio/src/LoRaRadio.cpp#L548

Preamble is defined here to 8: https://github.com/GrumpyOldPizza/ArduinoCore-stm32l0/blob/18fb1cc81c6bc91b25e3346595f820985f2267e5/system/STM32L0xx/Source/LoRa/Radio/sx1276/sx1276Regs-LoRa.h#L383

Is there a good method to easily change it in the config or what would be the best way of going about this in LoRaWAN.

**Comment by GrumpyOldPizza** [comment]
Not in the LoRaWAN standard. You can fool around that if you need to via the LoRaRadio class.
