### ISSUE TITLE
What is default encoding

### ISSUE THREAD

**Issue by mikemccauley** [GrumpyOldPizza/ArduinoCore-stm32l0#142]
Trying to understand what modulation is configured by 
LoRaWAN.begin(EU868);
so I can configure an LG-01 gateway.
What would be the resulting 
Frequency
Spreading Factor
Bandwidth
coding rate
and if necessary how can I alter them?

**Comment by battosai30** [comment]
Hi,

It might help : https://github.com/GrumpyOldPizza/ArduinoCore-stm32l0/issues/26

**Comment by GrumpyOldPizza** [comment]
See here: https://lora-alliance.org/resource-hub
