### ISSUE TITLE
no startup file found for stm32L073RZ

### ISSUE THREAD

**Issue by sajalbhargava** [GrumpyOldPizza/ArduinoCore-stm32l0#164]
hi ,
i am trying to compile code for stm32l073RZ , but it is not compiling i checked in source file and couldn't find startup_stm32l073 file 
is that the reason for board not compiling for NUCLEO-stm32L073RZ board?

**Comment by GrumpyOldPizza** [comment]
I am not sure where you problem is specifically. There is a L073 NUCLEO supported. That compiles directly, properly from the IDE. It does not reference to any startup_stm32l073.  So I am a tad lost as to what you are asking.

**Comment by GrumpyOldPizza** [comment]
No response, closing.
