### ISSUE TITLE
Linux path issue

### ISSUE THREAD

**Issue by SloMusti** [GrumpyOldPizza/ArduinoCore-stm32l0#17]
I have installed this repository as instructed on Ubuntu and ran into the following error:

```
/home/musti/.arduino15/packages/TleraCorp/hardware/stm32l0/0.0.5/tools/linux//dfu-suffix: no such file or directory Error compiling for board Cricket-L082CZ.
```
edit: above error output did not show correctly

The files are confirmed in the right place, however there is a redundant / in the path, which I can not figure out where from.

**Comment by GrumpyOldPizza** [comment]
Can you append a screen shot of the error log ?

**Comment by GrumpyOldPizza** [comment]
Got a fix for this, I'd think. The "//" might be the issue. Not sure why it
would be, because this works on my system quite well.

Can you check you have
a /home/musti/.arduino15/packages/TleraCorp/hardware/stm32l0/0.0.6/tools/linux/dfu-suffix
and that it's executable (and readable) ?

**Comment by SloMusti** [comment]
I have fug a bit deeper and found these are 32-bit executables, checked with:

```
file dfu-prefix 
dfu-prefix: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 2.6.24, BuildID[sha1]=e4dc89b4522cebf6e62294585516e4c7bb6e8fdb, not stripped
```
following this instructions: https://askubuntu.com/a/454452 I have installed 32-bit support and now it works well. This issue can be closed, but would be great to add the note to instructions.

**Comment by GrumpyOldPizza** [comment]
Switched to 64 bit binaries. Fixed.
