### ISSUE TITLE
Something off about reading from Serial

### ISSUE THREAD

**Issue by kevin192291** [GrumpyOldPizza/ArduinoCore-stm32l0#178]
Hello all,
I want to start by saying sorry about the lack of info I have on this. I am going to do my best to explain what I have found.
To start. I am attempting to use a Modbus library ([found here](https://github.com/smarmengol/Modbus-Master-Slave-for-Arduino)).
I am writing against the Grasshopper LoRa/LoRaWAN Development Board ([found here](https://www.tindie.com/products/tleracorp/grasshopper-loralorawan-development-board/))
The issue I am using an RS485 adapter that I have confirmed working using an arduino MKRWAN1310 (obviously with a very different chip controlling the MuRata module)

It appears to me that the issue occurs with the read operation in the library. I have connected the grasshopper board to another Serial device and do receive data from that. So, this is specifically an issue with how the Modbus library is reading in data.
I have tracked the issue down to this specific area:
```
    // check if there is any incoming frame
    uint8_t u8current;
    u8current = port->available();

    if (u8current == 0) return 0;

    // check T35 after frame end or still no frame end
    if (u8current != u8lastRec)
    {
        u8lastRec = u8current;
        u32time = millis();
        return 0;
    }
```

For some reason the "port" (that is serial1 from the grasshopper board) is not receiving data here. This only occurs when working with the grasshopper board. Yet, if I were to write something such as:
```
if (Serial.available()) {
    int inByte = Serial.read();
    Serial1.print(inByte, DEC);
  }
```
Everything works great.
so I am really stumped on this.

The reason I think there is something going on with the read is because I see `1400061128` being written on the serial line
on both boards. Yet the only board I get a response for is the mkr and not the grasshopper.

I do not see a light lit up on the rs485 board after a write from the grasshopper.... though I do when receiving on the mkr. I wonder if there is something more happening with the write? I increased the wait time as well to half a second, but no change.

If anyone out there could give me a hand with determining where to make a change. I would really really appreciate it.

Thank you all very much,
-Kevin

**Comment by kevin192291** [comment]
Pulling this down for now... Things just started to work and I honestly am not 100% sure why. I made edits to the modbus library, but I am not sure what ones made things work. I will work on figuring it out. It could be that the request from the serial port didn't include a CR/LF at the end... Though, I am not sure...

**Comment by GrumpyOldPizza** [comment]
I would think that the core issue at hand is that the UART driver uses DMA
to batch up a few back to back bytes. It's possible that the "end of
transmission" delay affects the modbus timing. In theory the USART
peripheral would implement the required timeouts directly ... Anyway might
be a good try to remove the DMA settings for the UART in question in the
corresponding variant.cpp file.

- Thomas
