### ISSUE TITLE
rename openocd script for Grasshopper to grasshopper-l082cz.cfg

### ISSUE THREAD

**Issue by Batilan** [GrumpyOldPizza/ArduinoCore-stm32l0#18]
The openocd script for the Cricket-L082CZ at https://github.com/GrumpyOldPizza/ArduinoCore-stm32l0/blob/master/variants/Grasshopper-L082CZ/openocd_scripts/grasshopper-082cz.cfg Should probably be named grasshopper-l082cz.cfg as the L082CZ is the name of the MCU and a similar name is also used for the Cricket and the Cicada. Now the referal in [boards.txt](https://github.com/GrumpyOldPizza/ArduinoCore-stm32l0/blob/ece327accd973f246c2bf4b92142e6350fb48c15/boards.txt#L34) fails.

**Comment by GrumpyOldPizza** [comment]
Done, closing out.
