### ISSUE TITLE
Murata LoRa Module availability

### ISSUE THREAD

**Issue by kevin192291** [GrumpyOldPizza/ArduinoCore-stm32l0#181]
Hello,
I was going to ask this in an active thread, but I didn't want to risk hijacking it so I figured I would start a new one.
The Murata cmwx1zzabz-078 is very important to a project I am working on, however I have been unable to get
my hands on these chips for production on PCBs of my own due to a fire that damaged a plant Murata's chips
are in part made at.
I am wondering if anyone knows of a source for these? Or If we are just waiting until Murata is back up and running?

Thanks all.

**Comment by battosai30** [comment]
I'm in the same situation but it's larger issue : all STM32 are unavailable. cmwx1zzabz works with STM32 so ...
