### ISSUE TITLE
sync-word-lora

### ISSUE THREAD

**Issue by hpssjellis** [GrumpyOldPizza/ArduinoCore-stm32l0#182]
Does LoRaRadio have the equivalent of [Sync-Word](https://forum.arduino.cc/t/what-is-sync-word-lora/629624/7) ?

```

 LoRa.setSyncWord(0xF3);           // ranges from 0-0xFF, default 0x34

```

I could hack a first byte must be a certain character, but sync-word actually seems like it is set by Symtech.

**Comment by GrumpyOldPizza** [comment]
There is only ::setPublicNetwork(bool enable).

Which toggles between the 2 official supported sync words.

**Comment by hpssjellis** [comment]
Thank you.
