### ISSUE TITLE
Does setTxPower have a maximum?

### ISSUE THREAD

**Issue by hpssjellis** [GrumpyOldPizza/ArduinoCore-stm32l0#183]
Any idea of the maximum setting for setTxPower?

1 is great for testing and seems to go about 50-100 m with my Antenna. I assume 14 is fairly good, but no idea what the maximum is and I don't see anything in the code setting a limit.

```
    LoRaRadio.setTxPower(1);    //default 14
```

P.S. The library is great. Having a lot of fun.

**Comment by GrumpyOldPizza** [comment]
The power level can be between 1 and 20. It is chip specific, as well as hardware/antenna specific.
