### ISSUE TITLE
How to add a new board

### ISSUE THREAD

**Issue by hpssjellis** [GrumpyOldPizza/ArduinoCore-stm32l0#188]
@GrumpyOldPizza I don't want to make you more grumpy, but would you be interested in a PR with the Portenta LoRa Vision Shield board?

How hard is it to add a new board? (Just duplicate a board, change it's name and go from there?)

I noticed Arduino [https://github.com/facchinm/ArduinoCore-stm32l0](https://github.com/facchinm/ArduinoCore-stm32l0)  just used your ```B-L072Z-LRWAN1``` board and altered it for each of the boards they were testing. They made a different repository  branch for each board. I am using their ```Vision Shield ``` [branch](https://github.com/facchinm/ArduinoCore-stm32l0/tree/vision_shield).

If you don't want a PR, I have my own library and that also is fine, I just have to make my own  Arduino board installation  json file

**Comment by GrumpyOldPizza** [comment]
No PRs at the moment. There is a lot of work from the STM32WB core coming back to STM32L0 ... so it's a bad moment in time.
