### ISSUE TITLE
Waiting on Serial Port will hang sketch when not available

### ISSUE THREAD

**Issue by Batilan** [GrumpyOldPizza/ArduinoCore-stm32l0#19]
Note that this is not a real defect: 

The  [while (!Serial) { }](https://github.com/GrumpyOldPizza/ArduinoCore-stm32l0/blob/90905080b93a6eba75add2d2e6bd4560eb8904a4/libraries/LoRaWAN/examples/LoRaWAN_ADR_Disable/LoRaWAN_ADR_Disable.ino#L59)  line (also used in many other example sketches) will hang the sketch when a serial port is not available.

This is completely logical but might be confusing (e.g. to those who use ST-Link which doesn't provide a serial port link by default)  when other means to detect a running sketch are used (like inspecting the LoRaWAN traffic on a backend server for an immediate end-to-end check). I'm using ST_Link by default and like to start with and end-to-end check when I expect everything to be OK (and work my way backward or forward when things fail). So working my way forward I found **my** "defect".

We might want to add a timeout waiting for the serial port and continue when it is not available?

**Comment by GrumpyOldPizza** [comment]
The examples cater to the standard configurations, which all have either USB (update throu USB), or a virtual serial port throu ST-Link (Nucleo).

There is no good reason to make the code any more complex than it needs to be.

You can always edit an example sketch and be done.

FYI what I do is to simply use a #define to use "Serial1" instead.
