### ISSUE TITLE
Support for Raspberry OS 64 bit

### ISSUE THREAD

**Issue by baarratia** [GrumpyOldPizza/ArduinoCore-stm32l0#199]
Hi! 

I'm trying to install this library on my Raspberry Pi 4 with Raspberry OS 64 bit (trying some crazy stuff...) but at the moment that I press Install in the Arduino IDE to install "Tlera Corp STM32L0 Boards" it doesn't work and shows this message:

> Tool arm-none-eabi-gcc is not available for your operating system

I've been looking up for a way to make it work, but maybe someone over here had a similar problem or knows the solution...

I've tried already using this on 32 bits and I've managed to install it and use it, but I had other problems, so now I'm trying with the 64 bit version and I'm stuck with this.

Thanks!

**Comment by GrumpyOldPizza** [comment]
Raspberry OS (Raspberry Pi XX) as host is not supported. No plans in doing so either.
