### ISSUE TITLE
Program via serial port

### ISSUE THREAD

**Issue by Protoneer** [GrumpyOldPizza/ArduinoCore-stm32l0#20]
I have a Grasshopper board and to program it via Arduino I need to hold the boot button while restarting the board. 

Can this board be programmed without having to put it in bootload mode manually?

I am also not able to get any of the serial examples to work. Do use Serial or SerialUSB? Tried both with no luck.

I am currently programming it from Win10. 

I am able to get the blink sketch to work. Any help will be much appreciated.

**Comment by GrumpyOldPizza** [comment]
Does any of the examples that print out bits and pieces show any output on
the serial monitor ?

**Comment by Protoneer** [comment]
No, the board does not expose a Serial Port so I can't open the serial monitor.

**Comment by GrumpyOldPizza** [comment]
Grasshopper has a USB port, which serves as "Serial". So the serial monitor
in the Arduino IDE should allow you to see data that a sketch prints out.

- Thomas

**Comment by Protoneer** [comment]
Yes... that was my understand as well.

From the picture below you can see there are no port selectable and that is why the Serial Monitor is not opening.

![image](https://user-images.githubusercontent.com/3835171/42534295-8037e0d6-84e0-11e8-9714-2769b5e50c08.png)

I do get an error message when flashing the board.(Manually have to put it into bootload mode) Is that normal?
![image](https://user-images.githubusercontent.com/3835171/42534444-dae70cdc-84e0-11e8-863d-270479a43275.png)

**Comment by GrumpyOldPizza** [comment]
I had never seen this error before.

If you look in the device manager then, is there another USB port after you
flashed this ?

Perhaps using Zadig, does it show up ?

- Thomas

**Comment by Protoneer** [comment]
Unfortunately no serial port...
![image](https://user-images.githubusercontent.com/3835171/42535800-84c0830c-84e4-11e8-9334-b8a125422bfd.png)

When I put it into bootloader mode I do get a STM32 BOOTLOADER device...
![image](https://user-images.githubusercontent.com/3835171/42535882-c174747a-84e4-11e8-8f10-41814402fe71.png)

I tried Zadig....
![image](https://user-images.githubusercontent.com/3835171/42536379-018cd59c-84e6-11e8-9d44-cf8f6d1c5d32.png)

Mmmmmm... wonder what it could be.

**Comment by GrumpyOldPizza** [comment]
Ok, in the images you selected a "Grasshopper" with 32MHz clock. You do
have a real Grasshopper board, right ?

I am puzzled as STM32 BOOTLOADER works, so it's not a hardware issue (bad
cable, busted board, bad USB port ...). You also indicated that the Blink
sketch makes the board blink, which tells me you most likely did not select
the wrong board. It's also not stuck in the bootloader ... Your screen-shot
shows a 32MHz clock, which allows USB to work (16MHz and lower disables
USB).

I have no idea what could be going on.

Could you try something like this here to list the USB devices:
https://www.nirsoft.net/utils/usb_devices_view.html

**Comment by Protoneer** [comment]
Managed to get DevManView... It still picks up when in bootloader mode but not in normal mode.

Yes its a real Grasshopper board I bought of Tindie. 

Does these boards come pre-programmed with special Bootloader firmware that I might have erased? Like the Arduino Zero...






Yes....I have assembled the Grasshopper from OSHpark PCB's...

**Comment by GrumpyOldPizza** [comment]
The bootloader is in ROM, factory programmed. You cannot nuke that one.

Perhaps you got the wrong PCB, or made a soldering mistake. There is a USB
connect pin via PA8.

Mine editing manually the variant.h file for Grasshopper and change the
following line:

#define STM32L0_CONFIG_PIN_VBUS           STM32L0_GPIO_PIN_NONE

**Comment by Protoneer** [comment]
Right... That did the trick!!! 

Is there a reason for having the dedicated pin?

Is there a way that I can make a $$$ donation for your help?

**Comment by GrumpyOldPizza** [comment]
The reason to have a pin is that the USB peripheral needs quite a bit of
power when turned on an waiting to connect. It's easier to monitor the
voltage.
