### ISSUE TITLE
Connecting LoraWAN to TTNv3 error MIC mismatch

### ISSUE THREAD

**Issue by rojikada** [GrumpyOldPizza/ArduinoCore-stm32l0#200]
Hello, does anybody have this working with the TTNv3? I am trying to use the lorawan module with TTNv3, however in the TTN console I get MIC mismatch.
The appEui = appEUI, DevEUI=devEui, JoinEUI=appKey and the specifiation is LoRaWAN 1.0.2 ?

**Comment by rojikada** [comment]
Aha! The problem was in having all zeroes in appEUI, after recreating the app with non-zero appEUI it started to work!

**Comment by salmanfarisvp** [comment]
Hi @rojikada , where did you get the the appEUI , devEUI and JoinEUI -> Did you generate from your own? Thanks.

**Comment by rojikada** [comment]
I just changed it within my code and the TTN web

**Comment by salmanfarisvp** [comment]
I see the JOINEUI is not available from the TTN, but another key can be generated. So can we use a random for that and match the same with the node firmware?

**Comment by rojikada** [comment]
I don’t understand what are you trying to do.

And as stated previously JoinEUI=appKey, which worked for me.

**Comment by salmanfarisvp** [comment]
Sorry for the confusion, I mean: When we register a new node in TTN, we need to provide the JoinEUI, so for a DIY project where do we get the JoinEUI if the manufacture did provide it with all?  Thanks. 

![image](https://user-images.githubusercontent.com/11945360/196606110-a45370a4-bb5a-4188-bfe6-3ab73112a944.png)

**Comment by rojikada** [comment]
You just generate one and put it to your code setup. If the device is not programmable, you might be on the wrong page.

**Comment by salmanfarisvp** [comment]
Got it, Thanks for your time. 🙂

I use the http://descartes.co.uk/CreateEUIKey.html to generate the EUI key.
