### ISSUE TITLE
[LoRaWAN] First packet is empty

### ISSUE THREAD

**Issue by battosai30** [GrumpyOldPizza/ArduinoCore-stm32l0#22]
Hi,

Every time I run for example LORAWAN_TTN_OTAA.ino , the first packet is empty : 

![image](https://user-images.githubusercontent.com/5184702/42808905-90dfb052-89b4-11e8-911a-15c8a5aed92c.png)

I have not this issue with my mDot868.

**Comment by GrumpyOldPizza** [comment]
That is correct.

We do send an empty packet to give the gateway a chance to update the
network parameters right away. It uses "port 0" for that. That is mainly
required for AU915/US915, where there is no CFLIST for OTAA.

**Comment by battosai30** [comment]
Ok so the empty packet is "included" with the join sequence and it's not a : 
```
   LoRaWAN.beginPacket();
        LoRaWAN.write(0xef);
        LoRaWAN.write(0xbe);
        LoRaWAN.write(0xad);
        LoRaWAN.write(0xde);
        LoRaWAN.endPacket();
```
That's "ignored" ?

**Comment by GrumpyOldPizza** [comment]
>  That's "ignored" ?

I has no payload and goes to port 0. So it's not a missing/bad application
data packet.

**Comment by battosai30** [comment]
Perfect !
Thanks
