### ISSUE TITLE
Support for Sigfox connectivity

### ISSUE THREAD

**Issue by kbesson** [GrumpyOldPizza/ArduinoCore-stm32l0#24]
Hi,

First, thank you for your amazing work ! :)

Are you planning to add Sigfox connectivity on Arduino for the Murata module ?

I can't find any native implementations of the Sigfox stack for Arduino. Only examples I've found are for the MKRFOX1200 that use a Sigfox modem with AT command set.

There are few examples projects in the Sigfox STCubeMX package but I don't think I will be able to port the stack for Arduino...

Thanks !

**Comment by GrumpyOldPizza** [comment]
There is nothing tentative planned at the moment. I am not in an area where
I could actually test SigFox. So it's hard to write software then.

**Comment by kbesson** [comment]
I understand, thanks for the quick reply @GrumpyOldPizza !

For information, you can check the Sigfox network coverage here : https://www.sigfox.com/en/coverage

And you can have free SigFox connectivity in the covered areas by requesting Murata for PAC files.

**Comment by GrumpyOldPizza** [comment]
Kevin, can you contact me offline via grumpyoldpizza@gmail.com ?

**Comment by kbesson** [comment]
Done ! ;)

**Comment by Batilan** [comment]
+1

**Comment by GrumpyOldPizza** [comment]
SigFox will not be supported in the current hardware. The other issue is the SigFox certification requirement. So ST did that for their B-L072Z-LRWAN1 platform. It seems to be impractical for now to do that for any other supported board ...

**Comment by nobodyguy** [comment]
Hello @GrumpyOldPizza - thank you for your amazing work and dedication!
What do you mean by "current hardware"? Sigfox is officially supported in the Murata chip. And the certification is not needed for development purposes.

**Comment by GrumpyOldPizza** [comment]
SigFox with the ST code requires some special GPIO mapping. We do not use this mapping as LoRaWAN is the prime target,

**Comment by nobodyguy** [comment]
Understood, thank you for the explanation.
