### ISSUE TITLE
how to set the clock speed

### ISSUE THREAD

**Issue by tve** [GrumpyOldPizza/ArduinoCore-stm32l0#29]
How do I set the desired clock speed for a sketch? Is there a way to dynamically change it?

**Comment by GrumpyOldPizza** [comment]
It is statically configured throu the Arduino IDE.

**Comment by tve** [comment]
Ugh. I'm using platform.io. Can't stand the IDE... DO you happen to know how it gets passed in? Else I'll have to make sense out of all the stm32l0_system.c clock code...

**Comment by tve** [comment]
Ok, found it: _SYSTEM_CORE_CLOCK_
Looks like I need to dig through the platform.txt and board.txt stuff to extract the configuration options in general...

**Comment by GrumpyOldPizza** [comment]
You have to hold BOOT while toggeling RESET to put the chip again into bootloader mode, if you use lower clocks. 

delays and sleep times do not have to be changed.
