### ISSUE TITLE
Firmware update utility?

### ISSUE THREAD

**Issue by trlafleur** [GrumpyOldPizza/ArduinoCore-stm32l0#3]
Will you be providing a utility to read firmware version and to allow to re-flash of new firmware version as they become available from muRata or ST-Micro??

I do see a FWUpdaterBridge.ino in the Arduino MRKWAN examples for the MRK1300 board..

**Comment by GrumpyOldPizza** [comment]
Arduino MKRWAN is using CMWX1ZZABZ as a slave to a SAMD chip. So they need to have some firmware on there to do the LoRaWAN part.

This source base here is for a standalone CMWX1ZZABZ. So you program the firmware ..
