### ISSUE TITLE
Q: what is the IRQ stuff in __analogReadInternal about?

### ISSUE THREAD

**Issue by tve** [GrumpyOldPizza/ArduinoCore-stm32l0#30]
I'm trying to understand some of the internals of the ADC code and am wondering what the IRQ dispatch in __analogReadInternal is supposed to do. Specifically: https://github.com/GrumpyOldPizza/ArduinoCore-stm32l0/blob/master/cores/arduino/wiring_analog.c#L84-L105
I'm not familiar with the ARM IRQ stuff... Thanks!

**Comment by GrumpyOldPizza** [comment]
That is a simple SVC wrapper so that this call is atomic.
