### ISSUE TITLE
I Nucleo LRWAN1 standalone.

### ISSUE THREAD

**Issue by pbecchi** [GrumpyOldPizza/ArduinoCore-stm32l0#31]
I am new to STM32 world! But I am interested to port a Sprinkler controller SW to USI Lorawan module.

The code is now written for Arduino uno and a Semteck module. I think that using your core library , porting should be easy.
Now I don't use LORAWAN but point to point RadioHead library to communicate between modules.
I can probably move to LORAWAN or port the RadioHead library to STM32...booth are valid alternatives!

To have a good low power profile is a must.I have now an average drain of 500uA.
To minimize power I need to use the I NUCLEO LRWAN1 as a standalone unit, final device will be based upon USI module.

**Comment by GrumpyOldPizza** [comment]
I-NUCLEO-LRWAN1 is not supported. STM32L052 has not enough FLASH or SRAM
for a LoRaWAN stack and an application. Hence there is no point of
supporting the USI Module at this point.

**Comment by pbecchi** [comment]
Thanks for your fast and clear answer!
Anyhow, since my first instance is to use RadioHead library and the actual application fit in an Arduino Uno, I should be able to use your core (or the ATM official one) without the use of LoraWAN libraries.

Am I right?

**Comment by GrumpyOldPizza** [comment]
I really have no idea. We are about to release a library that allows direct
LoRa communication similar to RadioHead. But that is based off the internal
SX1272/SX1276 driver that is also in use for LoRaWAN. It's also not
complicated to make that all work on the USI module, there is just not
enough FLASH/SRAM to do anything but have a hardcoded AT-Modem command set.

Please note that the soul of this Arduino Core is low power and LoRaWAN, as
well as USB CDC, HID & MSC support. So there is a certain bias to have a
solid feature set, which comes at a FLASH/SRAM consumption price. That does
not compare in any way to a Arduino Uno.

Last time I checked, the USI module was more expensive than the Murata
module. Is there any specific reason (technical) to use the USI module ?

**Comment by pbecchi** [comment]
Thanks again..... I will investigate your suggestion on Murata module......the only reason for thinking to the USI one was because I had this breakout board (I NUCLEO LRWAN1)available!   
Do you know of any cheap breakout board with the Murata module?

I never used before the STM32 arduino core, therefore I have no experience on the "core" minimum flash size.  Of course on a Uno, a small point to point Lora example will be around 10K ,but with other cores will be quite different....
Coming to LORAWAN i have another question : 
my application is basically a server that listen and execute  incoming commands.
I use a so called LoRa CAD mode, where the MCU wake up every 500ms to check incoming messages. 
For this kind of use LORAWAN class A seems  not to be the right choice.

 Is class B available right now? 
Is class C usable for a battery powered device?
Or I have any other choice?

**Comment by GrumpyOldPizza** [comment]
Can we take this discussion offline ?

grumpyoldpizza@gmail.com

**Comment by pbecchi** [comment]
Hi Thomas
Happy New Year!
I have finally a working example of a LoRa point to point CAD receiver.
The power drain in Cad mode is highly reduced, but not enought!
I have to learn better how to work with low power sleep mode of STM32L0xx, i havent found any documentation and i am spending a lot of time trying the various stm32l0_sleep() parameters.
Can you tell me any place where i can find documentation on various stm32l0_system.h and stm32l0_rtc.h routines ?

Thanks

Paolo

---- On lun, 13 ago 2018 15:11:58 +0200 notifications@github.com wrote ----

Closed #31.

**Comment by pbecchi** [comment]
Thanks Thomas

I believe I have understood most of your explanations…..I hope!

But this is power consumption I get from a using stm32l0_systems_sleep :

              stm32l0_system_sleep(0, 5000);         //0.75 mA
	Serial.println("Wake 5s sleep 0");
	stm32l0_system_sleep(1, 5000);          //1.39mA
	Serial.println("Wake 5s sleep 1");
	stm32l0_system_sleep(3, 5000);          //0.75mA
	Serial.println("Wake 5s sleep 3");
	stm32l0_system_sleep(2, 5000);          //0.85mA
	Serial.println("Wake 5s sleep 2");

This is not the current i was expecting to read, what I may be doing wrong?

Paolo

Sent from Mail for Windows 10

**Comment by GrumpyOldPizza** [comment]
What is your CPU speed ?

What other components on the board are powered ?

**Comment by pbecchi** [comment]
I haven t set cpu speed. I dont know how to change it!
I use an I NUCLEO LRWAN1 all jumpers dusconnected. This is before LoraRadio.init,  so i guess lora transeiver shoud not draw any current.
Thanks
Paolo

---- On gio, 24 gen 2019 19:48:29 +0100 notifications@github.com wrote ----

What is your CPU speed ?

What other components on the board are powered ?

**Comment by GrumpyOldPizza** [comment]
That does not make sense then.

The default CPU clock is 32MHz. With that SLEEP mode has 1700mA. You are
not seeing that.

I have never looked into the power consumption of the module on
I-NUCLEO-LRWAN1, nor do I understand what other power consumers are on
there (lie the analog RF switch).

**Comment by GrumpyOldPizza** [comment]
Ok, let's try this again. What if you just use a empty "setup()" and a empty "loop()" and measure power then ?

SX1272 should be powered down to about 100uA. The CPU should consume maximum power, which according to the datasheet should be about 6.25 mA typical, 7mA max (it says a while(1) { }  is 5.2mA, but that is not what "loop()" really does). 

The 2nd test is about bypassing all the other logic to establish a baseline for SLEEP mode. In this test, you have an empty "setup()", and "loop()" only contains a "__WFE();". With this you should be at 1750uA.

If your measurement diverge too much, you have either a measurement problem, or something else consumes power. The latter one you can figure out by a constant offset from the expected numbers, especially the one from the 2nd test.

N.b. that power measurement is tricky, and you need good equipment for that. I either use a Fluke 17B+ for min/max analysis, or a X-NUCLEO-LPM01A if the expected power is below 50mA.

**Comment by pbecchi** [comment]
Ok thanks...
I will trst tye way you suggest.

My multimeter is ok: it a long time i measure low power currents with Atmega 328 and with NRF52832. I also have a Nordic lowpower shield to measure current versus time.

I will be let you know soon...
Thanks.
Paolo

---- On ven, 25 gen 2019 13:34:41 +0100 notifications@github.com wrote ----

Ok, let's try this again. What if you just use a empty "setup()" and a empty "loop()" and measure power then ?

SX1272 should be powered down to about 100uA. The CPU should consume maximum power, which according to the datasheet should be about 6.25 mA typical, 7mA max (it says a while(1) { } is 5.2mA, but that is not what "loop()" really does).

The 2nd test is about bypassing all the other logic to establish a baseline for SLEEP mode. In this test, you have an empty "setup()", and "loop()" only contains a "__WFE();". With this you should be at 1750uA.

If your measurement diverge too much, you have either a measurement problem, or something else consumes power. The latter one you can figure out by a constant offset from the expected numbers, especially the one from the 2nd test.

N.b. that power measurement is tricky, and you need good equipment for that. I either use a Fluke 17B+ for min/max analysis, or a X-NUCLEO-LPM01A if the expected power is below 50mA.

**Comment by pbecchi** [comment]
These are my results:
Empty skecth 1.2mA.
Empty skecth with __WFE. 0.78 mA

All numbers are less than your estimates!

Paolo

---- On ven, 25 gen 2019 14:29:34 +0100 notifications@github.com wrote ----

__WFE() is an inline in the CMSIS include files.

Or you could use:

__asm__ volatile ("wfe");

**Comment by pbecchi** [comment]
How can i check/change clock speed?

---- On ven, 25 gen 2019 15:20:20 +0100 notifications@github.com wrote ----

Those are not my estimates, those are the numbers from the datasheet for
STM32L052.

The numbers that you are seeing do not make sense. The Arduino IDE allows
you to select 32MHz, 16MHz and 4.2MHz. None of those according to Table 29
(MSI and HSI16) and Table 33 (MSI and HSI16, FLASH on) come close to what
you are measuring. The closest is 4.2MHz (which you stated was not
selected) with 620uA/150uA, which means there is a constant other current
of about 600uA. It says that there is a STOP current of about 0.5uA. In a
previouse comment you stated that STOP mode gave you 0.75mA, and SLEEP
0.85mA. So that would fit together with about 600uA of current from
somewhere else.

But then again you stated that you did not change anything from the
defaults, which would make the software use a 32MHz clock ...

**Comment by GrumpyOldPizza** [comment]
As stated before there is a menu option in the IDE.

**Comment by pbecchi** [comment]
As a matter of fact it is set to 4.2 mHz!!
As possible reason for external 600uA current i see only a pull up resistor to SDA an SCL line (4k7).
Could this be the reason?

Paolo

---- On ven, 25 gen 2019 15:45:30 +0100 notifications@github.com wrote ----

As stated before there is a menu option in the IDE.

**Comment by GrumpyOldPizza** [comment]
The pullups should not be the reason. I can also not see any LED on the
schematics that usually would consume around 200uA.

I'd also assume you removed JP1, JP3 and JP4 ? This was LSM303AGR, LPS22HB
and HTS221 would not be powered.

Other than this, no idea. SX1272 is set to SLEEP mode (it's lowest power
mode) following a reset. The SPI bus is properly released.

The only other option would be the RF switch in the module. I do not know
which one that is, but both, the TX and RX GPIO are not driven ... So that
should be a low power state.

**Comment by pbecchi** [comment]
Jumpers are out!
Could not be the SPI NSS since need to be high for the Sx1278 to work?

I have not found any place the USI module schematics, i may try to ask dirdctely USI , very unlikely they give any answer!!

Paolo

---- On ven, 25 gen 2019 17:12:07 +0100 notifications@github.com wrote ----

The pullups should not be the reason. I can also not see any LED on the
schematics that usually would consume around 200uA.

I'd also assume you removed JP1, JP3 and JP4 ? This was LSM303AGR, LPS22HB
and HTS221 would not be powered.

Other than this, no idea. SX1272 is set to SLEEP mode (it's lowest power
mode) following a reset. The SPI bus is properly released.

The only other option would be the RF switch in the module. I do not know
which one that is, but both, the TX and RX GPIO are not driven ... So that
should be a low power state.

**Comment by GrumpyOldPizza** [comment]
Could all be. You got the source. wmsgsm42-board.c is the file to mess
around with.

**Comment by pbecchi** [comment]
Hi Thomas
Is this routine called at startup?
void WMSGSM42_Initialize( void )
{
    SX127xRadio = &SX1272Radio;

    stm32l0_gpio_pin_configure(RADIO_NSS, (STM32L0_GPIO_PARK_HIZ | STM32L0_GPIO_PUPD_NONE | STM32L0_GPIO_OSPEED_HIGH | STM32L0_GPIO_OTYPE_PUSHPULL | STM32L0_GPIO_MODE_OUTPUT));
    stm32l0_gpio_pin_write(RADIO_NSS, 1);

    stm32l0_spi_create(&RADIO_SPI, &RADIO_SPI_PARAMS);
    stm32l0_spi_enable(&RADIO_SPI);

    SX1272Reset( );
}

Coud this be the reason?

Paolo

---- On ven, 25 gen 2019 17:48:39 +0100 notifications@github.com wrote ----

Could all be. You got the source. wmsgsm42-board.c is the file to mess
around with.

**Comment by GrumpyOldPizza** [comment]
Which resistor ? I only see SB36 and SB37 in this path.

**Comment by pbecchi** [comment]
Yes i have replaced r37 and r37 with 2 jumpers where i can measure current to Mcu amd to Rf.



---- On lun, 28 gen 2019 13:19:42 +0100 notifications@github.com wrote ----

Which resistor ? I only see SB36 and SB37 in this path.

**Comment by GrumpyOldPizza** [comment]
Ok, 3rd attempt. Put in our loop only "STM32L0.stop()" (and #include
"STM32L0.h"). And measure then.

**Comment by pbecchi** [comment]
I have tested as you suggest and measuring at the Mcu jumper with STM32L0.sleep() 193 uA with STM32L0.stop() 1.5 uA. If i measure at the board 3.3v input still get previous high reading.
Just for my understanding ...how do i match sleep stop or stm32l0_system_sleep first parameter (0 to 3) to the low power modes of this table in the attachement?


---- On lun, 28 gen 2019 16:07:16 +0100 notifications@github.com wrote ----

Ok, 3rd attempt. Put in our loop only "STM32L0.stop()" (and #include
"STM32L0.h"). And measure then.

**Comment by GrumpyOldPizza** [comment]
Please do not use the system layer for now. It will change due to other
requirements.

1.3uA is not that bad ;-)

**Comment by pbecchi** [comment]
Thomas
Any advice to reduce flash size of the code.....i am a little over 64k!

Thanks

Paolo

---- On lun, 28 gen 2019 18:53:22 +0100 notifications@github.com wrote ----

Please do not use the system layer for now. It will change due to other
requirements.

1.3uA is not that bad ;-)

**Comment by GrumpyOldPizza** [comment]
There is no good advise there, other than to switch the module you are
using.

All things considered, 64K FLASH is just not enough. It's not enough to get
the LoRaWAN stack on there and have space for anything else, nor is it
enough for any more involved application, even if you limit yourself to
only using SX1272/SX1276 directly.

I do have zero interest on trying to squeeze out code size at the expense
of functionality. In fact it is very likely that the code size requirement
for the core arduino platform handling will increase.
