### ISSUE TITLE
Feature request: add setters for uplink and downlink counters

### ISSUE THREAD

**Issue by romansoft** [GrumpyOldPizza/ArduinoCore-stm32l0#41]
I'd like you to consider adding setters for uplink and downlink counters to help with testing the system at corner conditions when the counters roll over. Without these, it will take a very looong time to reach those conditions.

Also, could you please clarify these comments from another issue?
https://github.com/GrumpyOldPizza/ArduinoCore-stm32l0/issues/27#issuecomment-423232952
https://github.com/GrumpyOldPizza/ArduinoCore-stm32l0/issues/27#issuecomment-423239199

Will version 1.0.2 work correctly with 32-bit counter rollover, or should the network rejoin happen just before 16-bit counter expiry, as @SloMusti advises?

When the counter rolls over, does the application code need to do anything special (eg. force re-join)? Is there an error generated from send functions?

**Comment by GrumpyOldPizza** [comment]
User modifications of uplinj/downlink counters are pointless. For testing a system those had to be injected at a way lower level (i.e. syntheic test case).

There are no known rollover issues in 1.0.2. There is not rejoin required as pointed out in the other issue. The problem was observed with ST's code, which is derived off a LoRaMac-node 4.4.2 develop branch.

**Comment by romansoft** [comment]
@GrumpyOldPizza, when I say system testing, I mean interaction between a node and a network server., not just testing the module and firmware (although it's good to hear you had it covered). 
The network server implementations are all over the place with profiles for different lorawan versions. You would be surprised how many issues there are in corner cases and misconfigurations, even in commercial products. 
I, as any serious developer, would like to test these corner cases for the final system configuration before launching products into field. The alternative is to learn about issues later, the hard way.

**Comment by GrumpyOldPizza** [comment]
Please show me a real use case (not just an abstract one) where this makes sense, and would actually do the right thing.

**Comment by GrumpyOldPizza** [comment]
I'll add a "::setUpLinkCounter()". Not sure about the value, but easy enough to do. A "::setDownLinkCounter()" does not make sense, and this counter is driven by the gateway.

**Comment by romansoft** [comment]
As I said before, this is not be used in mission mode, but only during the system integration testing. Not having this is not a show stopper, but makes such testing harder than it should be. If this is a low effort add on (which I expected to be), it would be useful to have in the toolbox. 

setDownLinkCounter() is OK to be skipped.

**Comment by GrumpyOldPizza** [comment]
Ok. setUpLinkCounter() is not implementable right now. The backing EEPROM code enforces a strict increasing order. Applying all sorts of trickery does not seem to be worth it at this point of time. Perhaps when the stack will be upgraded to 1.0.3 or 1.1.

**Comment by romansoft** [comment]
Sounds reasonable. Thanks for trying.
