### ISSUE TITLE
How to Change clock speed - V2

### ISSUE THREAD

**Issue by rmeldo** [GrumpyOldPizza/ArduinoCore-stm32l0#47]
Hi,
If through the Arduino I choose the 4.2MHz, which doesn't support the USB, will I still be able to upload the sketches through the USB or is that functionality disabled as well?
I guess I will find out when I try but will my delays and sleep times have to change accordingly?
Thanks
Riccardo

**Comment by GrumpyOldPizza** [comment]
You have to hold BOOT while toggeling RESET to put the chip again into bootloader mode, if you use lower clocks.

delays and sleep times do not have to be changed.

**Comment by rmeldo** [comment]
Neat, thanks
