### ISSUE TITLE
PA13 function disable

### ISSUE THREAD

**Issue by ucdos123456** [GrumpyOldPizza/ArduinoCore-stm32l0#53]
can i ask if i want to disable the SWD function of PA13 and use it as a normal pin. how can i modify in the support software?  the code like below: `GPIO_PinRemapConfig(GPIO_Remap_SWJ_Disable, ENABLE);`

**Comment by GrumpyOldPizza** [comment]
You don't need to do anything special. Jut use "pinMode()" as usual.
