### ISSUE TITLE
TLera Corp Gnat

### ISSUE THREAD

**Issue by MartinNel** [GrumpyOldPizza/ArduinoCore-stm32l0#58]
The Gnat board provides the D8 and D9 pins which can be used for the Serial3 serial interface, just like for the Cicade, Cricket, LongCricket, etc. However the definition of the Gnat board is missing the Serial3 serial port in variant.h. This means I cannot recompile my code for the Gnat....
Can you add this, or is there a special reason not to have this?

**Comment by GrumpyOldPizza** [comment]
Fixed on github. Will be in the next downloadable release.
