### ISSUE TITLE
Downlink disable

### ISSUE THREAD

**Issue by SloMusti** [GrumpyOldPizza/ArduinoCore-stm32l0#61]
Just wondering if there are any options for downlink disable in order to be able to save power.  For example I know I can change the wait times and offsets like this, but diasble is nto performed in this case.

```
  LoRaWAN.setReceiveDelay(0);
  LoRaWAN.setRX1DrOffset(0);
```

Use-case scenario is to be able to disable downlinks and rx windows either in all cases and breaking direct LoraWan compatibility or disabling it when not expecting a downlink.

**Comment by GrumpyOldPizza** [comment]
Something like:

`
    LoRaWAN.setDownLink(bool onoff);
`

No, that is not supported. Should I add that ? Is control per RX1/RX2 needed ?

**Comment by SloMusti** [comment]
That would work, there is no need for separate RX1/RX2 control I believe as this functionality is really for purposes of going to sleep as soon as possible after transmission. This change would need to be implemented in a way, that you can use it prior to every transmission.

**Comment by GrumpyOldPizza** [comment]
Need to add a few other things to the LoRaWAN class. 

What about:

LoRaWAN.disableRxWindow1()
LoRaWAN.disableRxWindow2()

**Comment by GrumpyOldPizza** [comment]
Added:

LoRaWAN.setRxWindows(bool onoff);

So you want to first join (or continue from your previous join), and then disable the RxWindows(). However ADR will of course not work, LinkCheck will not work ... So not sure this is useful, other than for testing.
