### ISSUE TITLE
Sigfox examples

### ISSUE THREAD

**Issue by PAk-CatchFire** [GrumpyOldPizza/ArduinoCore-stm32l0#70]
Hello, how can I find a Sigfox example for this Core?
Regards

**Comment by GrumpyOldPizza** [comment]
There is no Sigfox support in this Core.

**Comment by NetSensors** [comment]
There is a sigfox example here but make sure you make the hardware mods mentioned as the TCO_VDD is powered by a different GPIO to the LoRaWAN one. I'm afraid it's not an arduino based example though.

https://github.com/aureleq/muRataSigfox

**Comment by GrumpyOldPizza** [comment]
That is incorrect. Other than on GNAT, X-CUBE-SFOX will NOT work. To get this working on GNAT you need to change the different VDD_TCXO pin, as well as the different mapping for DIO4/DIO5. Not that tricky, but painful.

In general SFOX on SX1276 for this module requires a different clocking for APB2 (higher power consumption) and a bunch of other non-trivial changes. Significant issue is the license that comes along with X-CUBE-SFOX, that kind of prevent and integration into ArduinoCore-stm32l0. However should SFOX ask me to do that with a different license ...
