### ISSUE TITLE
Support of PA boost on CMWX1ZZABZ

### ISSUE THREAD

**Issue by PAk-CatchFire** [GrumpyOldPizza/ArduinoCore-stm32l0#73]
Hi again.
On Murata's datasheet appears the following:
"Normal output power is +14dBm but a PA boost function can be selected to increase RF output to + 20dBm for long-range applications"

Does this core support that function?
Thank you

**Comment by GrumpyOldPizza** [comment]
Yes. Actually RFO goes to +15dBm. PA_BOOST to 20dBm nominally.

**Comment by PAk-CatchFire** [comment]
Thank you. How could I enable/disable it?

**Comment by GrumpyOldPizza** [comment]
You don't enable/disable that. Depending upon what TxPower you use the
proper path will be selectect.

**Comment by PAk-CatchFire** [comment]
Ok, I see....
So could I just call:
` LoRaRadio.setTxPower(14);`

and get PA_BOOST on automatically?

Regards

**Comment by GrumpyOldPizza** [comment]
Pretty much. Except up to 15dBm RFO is in use. But if you used 20dBm, then yes PA_BOOST is used.
