### ISSUE TITLE
Restarting the code execution using software

### ISSUE THREAD

**Issue by rishisharma920** [GrumpyOldPizza/ArduinoCore-stm32l0#81]
Hello, 

I am using the Grasshopper board for my testing and want to deploy a software-driven watchdog timer. Can you help me with the code snippet on how can I restart my code's execution from the firmware itself? For reference, I use the following when I need to restart my code on Arduino: void(*resetFunc) (void) = 0;

**Comment by GrumpyOldPizza** [comment]
Have you tried STM32L0.reset() ?

**Comment by rishisharma920** [comment]
I just tried and it worked. Thank you for your prompt response!
