### ISSUE TITLE
EEPROM code snipet 

### ISSUE THREAD

**Issue by Taher1322** [GrumpyOldPizza/ArduinoCore-stm32l0#82]
Hello Sir, I want to store a particular value into eeprom and before transmitting have to read and transmit over the lora network. Can you help me out with basic read/write operation in Grasshopper board. Small code of device performing read/write operation would be helpful.

Thank you

**Comment by GrumpyOldPizza** [comment]
The code is using the normal EEPROM class. 

https://www.arduino.cc/en/Reference/EEPROM

There are also examples included directly.

**Comment by Taher1322** [comment]
Sir, I am aware of that Arduino reference. what i need to understand is how can i use EEPROM address locations on cmwx1zzabz and store a value and read it later. 
Hope to hear from you soon
Thank You

**Comment by GrumpyOldPizza** [comment]
I am not sure what you are asking. The EEPROM class is the way to access
the EEPROM on STM32L082. There is code with the examples of how to do that.

If you are interested in how to directly access the underlying hardware,
then You might want to check out the reference manual.
