### ISSUE TITLE
How to set external clock

### ISSUE THREAD

**Issue by evandavey** [GrumpyOldPizza/ArduinoCore-stm32l0#83]
I have an external 8Mhz crystal connected to my board.  Do I just set STM32L0_CONFIG_HSECLK in the variant.h file?

**Comment by GrumpyOldPizza** [comment]
This is somewhat not really supported ... Is this still an issue, or can I close this out ?

**Comment by evandavey** [comment]
I'm no longer using this library, so not an issue for me.
