### ISSUE TITLE
GNSS begin() stuck due to PA10 being stuck high if noGPS connected on B-L072Z-LRWAN1

### ISSUE THREAD

**Issue by SloMusti** [GrumpyOldPizza/ArduinoCore-stm32l0#86]
I have been implementing the use of GNSS library on the B-L072Z-LRWAN1 board definition by adding 

```
#define STM32L0_CONFIG_PIN_GNSS_ENABLE    STM32L0_GPIO_PIN_PB2
#define STM32L0_CONFIG_PIN_GNSS_BACKUP    STM32L0_GPIO_PIN_PA4
#define STM32L0_CONFIG_PIN_GNSS_PPS       STM32L0_GPIO_PIN_PB7
#define STM32L0_CONFIG_PIN_GNSS_RX        STM32L0_GPIO_PIN_PA10_USART1_RX
#define STM32L0_CONFIG_PIN_GNSS_TX STM32L0_GPIO_PIN_PA9_USART1_TX
```
to the appropriate place here:
https://github.com/GrumpyOldPizza/ArduinoCore-stm32l0/blob/master/variants/B-L072Z-LRWAN1/variant.h#L39

https://github.com/GrumpyOldPizza/ArduinoCore-stm32l0/blob/master/libraries/GNSS/src/GNSS.cpp#L350
Due to the while loop, the library gets stuck as the pin for some reason does not go low, the options are as follows:
 * Hardware pull-up - could not find it on schematic
 * Something odd in the board configuration

Either way, the risk of this implementation is that upon hardware failure, the whole system may hang if for example the pin is held high for some reason. Implementing a check prior to begin() is an option to avoid it. @GrumpyOldPizza could you elaborate on the design choices why this is built this way?

**Comment by GrumpyOldPizza** [comment]
The code really need to detect a LO at some point of time, or it does not know that the chip on the other side is really present (it's really a scanning for UART data; default level is HI). I agree that perhaps a timeout might be in order. On the other hand, if that fails, many other spots might hang as well.
