### ISSUE TITLE
PWM

### ISSUE THREAD

**Issue by hallard** [GrumpyOldPizza/ArduinoCore-stm32l0#88]
May be a stupid question, but is it possible to change PWM pins just modifiyng variant.cpp?
IE I mean 
D8 (SWDIO) and D9 (SWDCLK) as PWM instead of A3 (PA3) and A4 (PA0)

I'm asking this because I don't find PWM for D12 and D13 in variant.cpp for grasshopper
![image](https://user-images.githubusercontent.com/2471931/59569989-6d4e0c80-9091-11e9-9cf3-21ada17380fe.png)

Thanks for your help

**Comment by GrumpyOldPizza** [comment]
Short answer is "no, that will not work".

**Comment by hallard** [comment]
Thanks, and no long one like "it's possible but not like that" ? I'm new to STM32 I thought it was possible to assign function to any pin?

**Comment by GrumpyOldPizza** [comment]
Nope, no long one. I could point you to the datasheet for STM32L082CZ, but at the end of the day, you can only assign a limited set of peripheral functions to each pin.

**Comment by hallard** [comment]
Makes sense, thanks
