### ISSUE TITLE
Enabling Watchdog Timer

### ISSUE THREAD

**Issue by rishisharma920** [GrumpyOldPizza/ArduinoCore-stm32l0#95]
Hello, 

I am using the Grasshopper board for my testing and want to deploy a watchdog timer. Can you help me with the code snippet on how can I enable a WDT? For reference, I use the following when I need to restart my code on Arduino: wdt_enable(WDTO_2S);

**Comment by GrumpyOldPizza** [comment]
STM32L0.wdtEnable(timeout)
STM32L0.wdtReset()

The "timeout" is in millisconds. Upper limit is 18000ms. Hope that helps.

**Comment by rishisharma920** [comment]
Hello, 

Thank you for your prompt reply. I tested out the functions and they worked. But, I have another issue, I cannot disable the watchdog timer before going to stop mode to be in low power mode. Because of which the board resets with a maximum sleep time of 18 seconds.

**Comment by GrumpyOldPizza** [comment]
Yep, that is correct. This is how the hardware works. See reference manual, 24.3.4.

**Comment by rishisharma920** [comment]
Sure, but is there a way to disable it, once enabled?

**Comment by GrumpyOldPizza** [comment]
No it cannot be disabled once enabled. That is kind of the whole purpose of a watchdog. If your system gets stuck by a software fault, there should not be a way that the software is able to disable the watchdog that could recover from such a fault.
