### ISSUE TITLE
ContinuosWave mode in LoRaRadio and LoRaWAN libraries

### ISSUE THREAD

**Issue by SloMusti** [GrumpyOldPizza/ArduinoCore-stm32l0#97]
Currently working on on-board VSWR meter implementation for a LoRaWAN device, such that the antenna matching can be measured when device is actually used. The particular challenge is to create a spectrum sweep and send results via LoRaWAN.

This pull request enables the scanning via uart, useful for lab work.
https://github.com/GrumpyOldPizza/ArduinoCore-stm32l0/pull/96

Same method can not be applied to LoRaWAN library however as there is a mac layer in-between.  There is some implementation for the compliance mode testing, however https://github.com/GrumpyOldPizza/ArduinoCore-stm32l0/blob/master/libraries/LoRaWAN/src/LoRaWAN.cpp#L3253 this would then need to be wrapped in a function that is callable from the user code. 

@GrumpyOldPizza or anyone with more knowledge how/if `mlmeReq` can be issued to complete this.

**Comment by GrumpyOldPizza** [comment]
Added an API for this.
